[versions]
# SLF4J releases: http://www.slf4j.org/news.html
slf4j = "2.0.6"

# Jackson releases: https://github.com/FasterXML/jackson/wiki/Jackson-Releases
# Make sure to align with the major version of Jackson that Arrow uses.
# See https://github.com/apache/arrow/blob/f10f5cfd1376fb0e602334588b3f3624d41dee7d/java/pom.xml#L39
jackson = "2.13.5"

# JUnit releases: https://junit.org/junit5/docs/current/release-notes/index.html
junit = "5.9.2"

# AssertJ releases: https://github.com/assertj/assertj-core/tags
assertj = "3.24.2"


[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
jackson-bom = { module = "com.fasterxml.jackson:jackson-bom", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
